### ISSUE TITLE
API-Key Management

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/sbc-apigw#29]
- [ ] #30
- [ ] #31
- [ ] #32
- [ ] #33

**Comment by thorwolpert** [comment]
the designs are all private facing, sorry nothing to open here

**Comment by vortex-hue** [comment]
alright, does the issue still needs help on solving it?

**Comment by thorwolpert** [comment]
it's with the team working on it now.

**Comment by vortex-hue** [comment]
alright, am looking for some issues to volunteer on actually

**Comment by thorwolpert** [comment]
I'll have a look an see if we have any good first issues.
That should also give you the  " [x] has bc gov experience " check
There's also opportunities, small and large, here https://marketplace.digital.gov.bc.ca/opportunities
you can also email me thor at wolpert . CA

**Comment by vortex-hue** [comment]
hi Thor, the email address you wrote isn't complete though, and am open to contributing to both javascript and python based software
